import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ezen Garden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" align-top">
          <div className="flex justify-between">
            <a href="/" className="p-4">
              <Image src="/favicon.ico" alt="Ezen Garden" width={100} height={100} />
            </a>
            <div className="flex items-center">
              <a href="/" className="p-4">Home</a>
              <a href="/about" className="p-4">About</a>
              <a href="/contact" className="p-4">Contact</a>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
