import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { getDictionary, HomeProps } from '@/dictionaries/dictionaries'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ezen Garden",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {
    children,
    params: { lang },
  }: {
    children: React.ReactNode;
    params: HomeProps;
  }
) {
  const dict = await getDictionary(lang);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" align-top">
          <div className="flex justify-between">
            <a href="/" className="p-4">
              <Image src="/favicon.ico" alt="Ezen Garden" width={100} height={100} />
            </a>
            <div className="flex items-center">
              <a href="/" className="p-4">{dict.navbar.home}</a>
              <a href="/articles" className="p-4">{dict.navbar.articles}</a>
              <a href="/contact" className="p-4">{dict.navbar.contact}</a>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
